version: 2

sources:
  - name: glue_silver
    description: "Zone Silver - Données nettoyées et partitionnées par Spark (AWS Glue Catalog)"
    database: awsdatacatalog # Nom standard pour le catalogue Glue dans dbt-athena
    schema: jobradar_db      
    tables:
      - name: silver_jobs
        description: "Offres d'emploi dédupliquées et structurées par le pipeline PySpark"
        columns:
          - name: job_id
            tests:
              - unique
              - not_null
          - name: salary_min_numeric
            description: "Salaire minimum extrait et converti en Integer"