version: 2

models:
  - name: stg_adzuna
    description: "Modèle Staging normalisé pour les offres Adzuna"
    columns:
      - name: job_id
        description: "Identifiant unique de l'offre"
        tests:
          - unique
          - not_null

  - name: stg_france_travail
    description: "Modèle Staging normalisé pour les offres France Travail"
    columns:
      - name: job_id
        description: "Identifiant unique de l'offre"
        tests:
          - unique
          - not_null