
name: 'jobradar'
version: '1.0.0'
profile: 'jobradar'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# --- CONFIGURATION DU SCORING ---
vars:
  base_score: 20
  
  # Expérience & Statut
  bonus_junior_flag: 25
  bonus_junior_title: 15
  penalty_senior: -40       # On tape un peu plus fort sur le Senior
  penalty_lead: -50     
  penalty_mid_experience: -20 # Nouveau : pour les offres > 2 ans
  penalty_high_experience: -50 # Nouveau : pour les offres > 5 ans    
  penalty_technician: -15
  penalty_hidden_seniority: -10  # Pour les phrases type "expérience significative"
  
  # Éthique
  penalty_ethics_light: -15 # Banques, Finance...
  penalty_ethics_heavy: -60 # Armement, Guerre...
  
  # Technos
  bonus_cloud_stack: 12
  
  # Préférences de vie
  bonus_remote: 15
  bonus_freshness: 5

# --- CONFIGURATION DES MODÈLES ---
models:
  jobradar:
    staging:
      +materialized: view  # Les fichiers de staging sont souvent des vues
    marts:
      +materialized: table # Les couches silver/gold en tables pour la perf
      +table_type: 'hive' # Spécifique à Athena pour créer des tables classiques
      +format: 'parquet'  # On reste sur du Parquet pour la performance FinOps
