name: Deploy Infrastructure (Terraform)

on:
  push:
    branches: [ main ] # Se lance à chaque push sur main
    paths:
      - 'src/lambda/**'
      - 'terraform/**'
  workflow_dispatch: # Permet de déclencher manuellement le workflow depuis l'interface GitHub

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies for all Lambda
        run: |
          # On boucle sur tous les dossiers pour installer requests partout
          for dir in adzuna france_travail jsearch jooble; do
            echo "📦 Installation des dépendances pour $dir..."
            pip install requests --target src/lambda/$dir/
          done

      - name: Terraform Init & Apply
        working-directory: ./terraform
        env:
          TF_VAR_jsearch_api_key: ${{ secrets.JSEARCH_API_KEY }}
          TF_VAR_jooble_api_key: ${{ secrets.JOOBLE_API_KEY }}
          TF_VAR_adzuna_app_id: ${{ secrets.ADZUNA_APP_ID }}
          TF_VAR_adzuna_app_key: ${{ secrets.ADZUNA_APP_KEY }}
          TF_VAR_ft_client_id: ${{ secrets.FRANCE_TRAVAIL_CLIENT_ID }}
          TF_VAR_ft_client_secret: ${{ secrets.FRANCE_TRAVAIL_CLIENT_SECRET }}
          TF_VAR_athena_staging_dir: "s3://jobradar-athena-results-manuel-cloud/athena-temp/"
        run: |
          terraform init
          terraform apply -auto-approve